### ISSUE TITLE
Release an output through Airlock

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#124]
As the last part of https://github.com/opensafely-core/airlock/milestone/1, we should run the [TPP database schema](https://jobs.opensafely.org/opensafely-internal/tpp-database-schema/) job, and request that the outputs are released via Airlock.

We should give the output checkers a heads up that this is coming, but in order to test the documentation and general usability, we should not provide more assistance unless they ask for help.

**Comment by rebkwok** [comment]
An output has been release from TPP via Airlock
https://jobs.opensafely.org/opensafely-internal/tpp-database-schema/releases/01HRF16YRZ78AXZ2AH4E0B2E0F/

**Comment by rebkwok** [comment]
Observations along the way:
- entering airlock ID into the output request form is tedious. If researchers are going to use the current hybrid process, we should consider some other format or way of identifying the release (maybe username/workspace plus first 5 or 6 characters of ID?)
- We don't yet show file metadata (e.g. timestamp); I had run the initial job without force-run-dependencies, so the files hadn't actually been updated. This would have been more obvious if we could see the date of the file on Airlock.
- After I re-ran the job, we couldn't easily update the file, because we don't store/check the file hash yet. We're just relying on filename, and if the file is already added to a request, it can't be added again (and we don't have a notion of updating yet). This probably goes along with per-file approvals, so an approval is associated with a particular file hash and if the file's updated, it needs to be re-approved.
- Helen had viewed the html file already, and after it was updated, she continued to see the old file until she logged out and in again. Simon and I both saw the updated version.
