### ISSUE TITLE
Support downloading files to remote desktop in secure environment

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#126]
To allow users to explore their outputs (especially tabular data), and for output checkers to perform disclosivity checks on tabular data, we need to support users downloading files through Airlock onto their remote desktop in the secure environment.  This will allow them to open files in eg a spreadsheet program.

Each page showing a file should have a "Download" button and the downloaded file should have a suitable filename.

The documentation should be updated to explain this.

UPDATE:
Downloads will only be available for files in release requests, and only for output checkers. We won't add restrictions on the file type (tabular data is both the most likely use case for downloaded, but also the most risky).  All downloads will be logged (full access log functionality will be part of another ticket).

**Comment by bloodearnest** [comment]
There's a discussion to be had about this.

I think we should only allow downloading of files a) for output-checkers b) from a release request and c) only tabular data.

My reasons are:

1) Every time a user downloads a file, there's the potential for that file to exist outside of our control. We cannot audit access to it, we cannot delete it.  Whilst downloading via airlock is better than the current system (where any user can view and *edit* any file, and we've no audit), I still think we should minimise this.

2) I would argue the browser is the best tool for viewing images, plain text, and html.  None of the native tools provide any advantage for read-only use.  The only reason users use notepad or an image tool is because they are navigating the host filesystem, and thats the only option.  tabular data is a known weakness of a browser viewing implementation, so we should just allow downloading for that

**Comment by LFISHER7** [comment]
I'm pretty sure 3 is true, but it may be worth asking other researchers. If you're using the spreadsheet to dig further into outputs as a researcher, that should arguably be scripted.

**Comment by bloodearnest** [comment]
I noticed via https://github.com/ebmdatalab/team-manual/pull/658 that the docs recommend opening html file is vscode to check for js and comments.  

Is this something we still want to support?

We can show the raw html in airlock very easily if needed.

It would be nice if we didn't need vscode on level 4.

**Comment by LFISHER7** [comment]
Ah yes, I'd forgotten about that. We'll want to support that as long as we continue to allow html outputs but if airlock can support viewing the raw and rendered html then I think we can remove vscode.

**Comment by rebkwok** [comment]
Re #3: we've decided to allow downloading of any file type (by output-checkers and release request files only). I updated the description in the ticket but didn't add to the comments, sorry.

**Comment by bloodearnest** [comment]
> Re #3: we've decided to allow downloading of any file type (by output-checkers and release request files only). I updated the description in the ticket but didn't add to the comments, sorry.

OK.

That will mean we need to maintain TTP having native programs installed to view these files when downloaded, then.

**Comment by rebkwok** [comment]
> That will mean we need to maintain TTP having native programs installed to view these files when downloaded, then.

I mean, we can change this if we need to. I was just going by the discussion in the meeting yesterday - I'm not sure we were thinking about the required system software then.
