### ISSUE TITLE
Double scrollbar issues for file content

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/airlock#223]
The iframe height for file content is set to 1000, which for large files results in double scrollbars, because the iframe is taller than the screen size. With long files, you scroll inside the iframe, but when you get near the end of the content, you need to scroll the outer scrollbar in order to bring the overflowed iframe into view (or with a trackpad, if you wait a second it will switch the focus to the outer scroll bar and scroll the right thing, but it's still annoying). 

Now that CSVs are shown as paginated tables with simple-datatables, this is more apparent, because the actual displayed content is smaller, even for long tables. 

![Screenshot from 2024-04-05 15-58-13](https://github.com/opensafely-core/airlock/assets/6770950/b5b9e3f4-d6da-4f6e-b82b-1386d7cdfe4d)

I think we probably want to fix the iframe or its containing div to a height that fits on the screen, and make all the scrolling happen within the iframe. Users already have the option to view the file in a separate tab if scrolling within the iframe isn't optimal for some files.

**Comment by rebkwok** [comment]
https://bennettoxford.slack.com/archives/C63UXGB8E/p1713442301472299

**Comment by madwort** [comment]
I was just looking at this, and the default behaviour at the moment is for the screen to scroll down so that the group is at the top of the screen, giving a kind of "full-screen" effect where the airlock banner etc is generally hidden & the user can do most of their work with only the most relevant buttons on screen. Like this:


<img width="1387" alt="Screenshot 2024-04-26 at 16 04 32" src="https://github.com/opensafely-core/airlock/assets/2082895/160f3011-87e5-4416-a36b-574e3186a0db">

When viewed like this, I think the iframe does generally fit on the screen. And although there are then two scrollbars for e.g. a long HTML I think that's fine. I think that the simple-datatables view of CSV files isn't really fine, though, as it's paginated & the pagination controls are hidden. I think what we should do is change the `[perPage](https://fiduswriter.github.io/simple-datatables/documentation/perPage)` setting to something that will always fit inside the current size of the iframe. The complication with doing this is that I think we're using a pre-processed version of the JS that's [come from job-server with a default perPage setting of 25](https://github.com/opensafely-core/job-server/blob/main/assets/src/scripts/_datatable.js#L78), so I'm not sure how we'd initialise the simple-datatables view with a different configuration.
