### ISSUE TITLE
Completed review button/state

### ISSUE THREAD

**Issue by madwort** [opensafely-core/airlock#254]
> Nice to have - a button i can click to show that i have completed the review - as second reviewer i wouldn't want to either release, or reject (the available final end of action button options), but it would help me feel like i had finished the process if i could press something to 'submit review' or something, instead of just not clicking any more 'approve buttons' (unless i was meant to press something and i missed that)

from Rose

Update: this idea has been developed more.

Louis has pointed out
1) we ideally want to preserve review independence
2) we want to provide a chance to reivew/harmonise votes/comments before sharing with the user

This means we will likely need to introduce a formal workflow/state to track the individual checker completion, and then a final state for one of the checkers to review and then send to user.

The idea being that other checker's comments and votes are not visible to the other until both have completed their initial review. And they are not visibile to the user until one of them has signed of on the joint review.

**Comment by bloodearnest** [comment]
I think this might effectively just be "send notifications"? A bit like commenting as you go, and then submitting a review in a Github PRIt's analogous to the way it works in the current word doc based process. It would reduce notification fatigue.

The notification we send could just basically be the audit log of the output-checker's activity. If we track the last time a user interacted with a request, we can send them all activity since they last viewed.

It would be tracking an audit log "Output checker foo completed review" too.

**Comment by bloodearnest** [comment]
related to #326

**Comment by madwort** [comment]
kind of a duplicate of #326
