### ISSUE TITLE
Add RETURNED state

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#326]
To improve the workflow around the back-and-forth between researchers and output checkers, we want to restrict what each type of user can do at certain times.  This means formalising the concept of a "round of review", and adding a new state for a review request: `RETURNED`.

While a request is in this state, output checkers should not be able to interact with a request.  And researchers should only be able to update a request while the the request is in the `PENDING` or `RETURNED` state.

Moving a request to the `RETURNED` state should require a deliberate action by an output checker.  This should only be available once every file in the request has approval decisions from two output checkers in any round, or any two decisions in the current round.  Although this information could be reconstructed from the audit log, it may be better to have a way of explicitly identifying decisions made in the current round.

A notification should be sent when a request moves to the `RETURNED` state; this should send an email to the researcher and update the corresponding GitHub issue. (This will also require some changes to job-server)

A researcher should be able to withdraw a request at any point before it is released.  There does not appear to be possible via the UI, but the `RequestStatus` state machine should be updated to allow withdrawing a request in the `RETURNED` state.

Addressing this will require updating the documentation (perhaps to include a state diagram).  Changes to the documentation should be reviewed by a member of the output checking team.

**Comment by rebkwok** [comment]
> This should only be available once every file in the request has approval decisions from two output checkers in any round, or any two decisions in the current round.

What happens when a file is approved by one reviewer and rejected by another because it needs information, but doesn't get changed? E.g.

Round 1:
File 1: approved by R1 & R2
File 2: approved by R1, rejected by R2
File 3: approved by R2, rejected by R1
R1 (or R2) click button to Return to researcher

Researcher makes changes to file 2, answers a question about file 3 but doesn't change it, and clicks Submit again.
Round 2
File 1 already has 2 approvals, doesn't need re-reviewed.
File 2 has been changed, needs re-reviewed by both R1 and R2
File 3 hasn't been changed. Does it only needs reviewed by R1, who rejected it before? Or do we need both R1 and R2 to review again, because a question has been answered? The response to the question could potentially affect R2's previous decision to approve. If so, we need to reset approvals in some way at the end of a round for any individual file that was rejected by at least one reviewer, and only files with 2 approvals in a single round would be carried forward to the next round.

**Comment by rebkwok** [comment]
Also needs an update to the notifications, to send emails/update issue when a round is completed. We have the author's username in the notification payload for emailing when a request is returned; we don't have the output checkers for emailing when a request is re-submitted (but we could easily get those from the file approvals if we wanted to do that).
We might want another notification event type for re-submission after a review round.

**Comment by rebkwok** [comment]
Do we also need a new FileApprovalStatus for needs info/changes? Something that isn't approved or rejected but does indicate it's been reviewed?

**Comment by inglesp** [comment]
> File 3 hasn't been changed. Does it only needs reviewed by R1, who rejected it before? Or do we need both R1 and R2 to review again, because a question has been answered?

I think it only needs review by R1.  As R2 has already approved it, after R1 approves it, it will have two approvals.  If R2's already approved, I don't see how the researcher answering the question would need R1 to revisit.

**Comment by inglesp** [comment]
> Also needs an update to the notifications.

Good point, will update.

**Comment by inglesp** [comment]
> Do we also need a new FileApprovalStatus for needs info/changes? Something that isn't approved or rejected but does indicate it's been reviewed?

That's a separate concern.

**Comment by rebkwok** [comment]
This is on hold pending decisions on whether we're going to enforce the process with Airlock.
Branch `returned` does most of the non-IU work so far.

**Comment by rebkwok** [comment]
UI part split out into separate ticket #388
