### ISSUE TITLE
Ensure rubric from .docx is shown to users in Airlock

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#403]
The Word doc includes a rubric with instructions for researchers.  We should talk to Louis about exactly which parts of this need to be shown to users in Airlock, and when.

**Comment by evansd** [comment]
## Existing rubric taken from form and docx

Intro text:

> Please fill in this form to request a release of your study data to your GitHub repo. This is a process that is imposed on us by external requirements, due to working on highly sensitive data, and is common to all similar data access environments. We are working to minimise the workload for OpenSAFELY users and staff as far as possible, including through technical work around automated disclosure control.
> 
> This form and process is a first iteration: we are keen to hear feedback on how to reduce the work and make the process smoother. You will be able to leave feedback at the end of this form when completed or email us ([datarelease@opensafely.org](mailto:datarelease@opensafely.org)).
>
> TIMESCALE: OpenSAFELY will return the reviewed form to the applicant’s email within 1 week of submission, and usually sooner; small releases will likely be approved faster.

Minimisation:

> The number of study outputs requested for review must be kept to a minimum and include only the results you absolutely need to export. Because each data release entails substantial review work, and we need to retain rapid turnaround times, external data releases should typically only be of results for final submission to a journal or public notebook; or a small number of necessary releases for discussion with external collaborators. Please confirm you have read and understand and are complying as far as possible.


Permitted Study Results Policy _(appears in docx but not in form)_:

> Check your results adhere to the Permitted Study Results Policy:
> https://www.opensafely.org/policies-for-researchers/#permitted-study-results-policy

Data release principles:

> Have you applied all necessary and relevant disclosure controls to the data for release? These are detailed at
> https://ukdataservice.ac.uk/media/622521/thf_datareport_aw_web.pdf

**Comment by evansd** [comment]
Note that linking to external pages from inside Airlock won't be helpful as these won't be accessible from the secure environment.

**Comment by LFISHER7** [comment]
I think it would be good to surface bits of the existing text at different stages of the review, which we tried to do with the [google form version](https://docs.google.com/forms/d/e/1FAIpQLSd_B_JE6Kaq3g-oyDKgjXl1L-NmUH-ILmEbo62z6vsFXha6rA/viewform). Below is suggested text and the stage it should be surfaced

## Start of the request

Review requests currently start when a user adds a file to a request. If there was a distinct `Start release request` button, this text could then be shown.

### Intro text

Please select the files you would like released providing a description of the file contents and the disclosure controls you have applied to support review of the outputs.

The requested outputs will undergo independent review by two OpenSAFELY output checkers who will check that the outputs are within the scope of your original project proposal and that they do not present any disclosure risks. Please allow up to 5 working days for feedback on your request. Small releases will likely be approved faster.

### Data minimisation

The number of study outputs requested for review must be kept to a minimum and include only the results you absolutely need to export from the server. Because each data release entails substantial review work, and we need to retain rapid turnaround times, external data releases should typically only be of results for final submission to a journal or public notebook; or a small number of necessary releases for discussion with external collaborators. Please describe why the data release is necessary to help you meet your project purpose.

**Dropdown Options**:

* Sharing intermediate results with collaborators
* Results for final report/presentation manuscript
* Other (if selected a free text field should be provided)

### Data release principles

Checkboxes

- Please confirm that you have read the OpenSAFELY documentation on data release 
- All outputs from the NHS England OpenSAFELY COVID-19 service must be aggregated data with small number suppression applied. The service operates as a trusted research platform where no patient record level data is permitted to be extracted from the platform. You MUST NOT request the release of any information (e.g. name, listsize) that identifies, or could identify, ICBs, Local Authorities (including MSOA identifiers), Primary Care Networks (PCNs) and individual GP practices from the Level 4 results server. Please confirm and that your results are in line with this policy.

## During file selection

### Context

Please describe the contents of this output to help reviewers. This includes:

* Variable descriptions
* A description and count of the underlying population for each output if it is not included in the output.
* Specify population size and degrees of freedom for all regression outputs.
* Relationship to other data/tables which through combination may introduce secondary disclosive risks.

### File specific details

This could be shown if a user selects a html for review

Checkbox 

**html files** 
html files can only be released if you are producing a report that is intended to be hosted on reports.opensafely.org. Please check this box if that is the case. If not, please produce the output as another of the support file types.

## End of the request

### Disclosure concerns

We expect that all users will minimise disclosiveness of any proposed release and follow guidance. Please tell us if you feel there are any potential disclosure issues, or edge cases, listing the specific files where this issue arises).

Freetext field

## Checklist

Checkboxes 

Have you redacted all low counts?
Have you rounded all counts?
Have you supplied underlying counts for all of your results?

### Review priority

We aim to respond to all review requests within 5 working days of submission, and usually sooner. We can occasionally commit to expedited review. Acceptable reasons for this include deadlines for conference submissions or deadlines for responding to peer review comments.

Please indicate below if you would like a prioritised review. Please only request this if absolutely necessary.

Checkbox + date selection

**Comment by inglesp** [comment]
Thanks @LFISHER7 for your detailed notes.  We think we've made the important changes in #423, and once #630 is done, I think we'll have done all we've got time for for now.
