### ISSUE TITLE
Airlock failing to show file contents

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#416]
From @andrewscolm via tech-support:

> airlock is failing to show the added files from the *_descriptive folder of [this request](https://github.com/ebmdatalab/opensafely-output-review/issues/884#issuecomment-2185257886). After 6 mins it is still saying "Loading table data.."

 * [Source Slack thread](https://bennettoxford.slack.com/archives/C065F8P58AW/p1719220282904469)
 * [Discussion Slack thread](https://bennettoxford.slack.com/archives/C069YDR4NCA/p1719220616589069)

**Comment by rebkwok** [comment]
This isn't related to the files themselves being too large, but due to the fact that the output is tab-separated and isn't renderable as CSV. It has a solution - the view-as-plaintext option (#410) will let these files be viewed. I'm investigating whether the issue is the width of the single column that the file is interpreted as - if we can't load the CSV file, we can handle the error by either using a text renderer or displaying a message to the user
