### ISSUE TITLE
Get HTMX to show messages so that old messages are not shown later

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/airlock#464]

**Comment by evansd** [comment]
Closing as I can't find any instances where this actually happens. Methodology was:
 * Click around a bit and fail to find any.
 * [Ask in Slack](https://bennettoxford.slack.com/archives/C069YDR4NCA/p1721038161495159) if anyone knew (they didn't, or thought maybe they'd be fixed via other changes).
 * Search for `hx` in `airlock/views/` and check whether I could see any places where were setting messages but not using `HX-Redirect`.

If we do need to come back to this then I think the solution would be a bit like the one outlined here:
https://blog.benoitblanchon.fr/django-htmx-messages-framework/

That is, use middleware to consume any messages in response to a HX request and set the message contents in an `HX-Trigger` header.

I'd be tempted to render the messages to HTML first and supply that in the header rather than using client-side templating as the solution above does. That seems more in keeping with the HTMX spirit of keeping all the presentational logic server-side.

We'd need to add some sort of invisible "locator" element above the `alerts` partial here so that HTMX knows where to inject the messages:
https://github.com/opensafely-core/airlock/blob/3f0f815856906174ea37673b0d330418d410bead/airlock/templates/base.html#L33

Slack thread:
https://bennettoxford.slack.com/archives/C069YDR4NCA/p1721038161495159
